export default [
  "$PERSON $TRANSITIVEVERB $PERSON",
  "$PEOPLE $TRANSITIVEVERB $PEOPLE",
  "$PERSON $INTRANSITIVEVERB and $TRANSITIVEVERB $PERSON",
  "We dock at $PLACE where $PLACEDESCRIPTOR",
  "$PERSON $INTRANSITIVEVERB",
]
